export { SENDLIB_CLIENT, SENDLIB_MODULE_OPTIONS } from './sendlib.constants.js';
export type {
  SendlibModuleAsyncOptions,
  SendlibModuleOptions,
  SendlibOptionsFactory,
} from './sendlib.interfaces.js';
export { SendlibModule } from './sendlib.module.js';
export { SendlibService } from './sendlib.service.js';

export {
  Sendlib,
  SendlibAbortError,
  SendlibApiError,
  SendlibAuthenticationError,
  SendlibBatchFailedError,
  SendlibBatchWaitTimeoutError,
  SendlibConfigError,
  SendlibError,
  SendlibForbiddenError,
  SendlibNetworkError,
  SendlibPayloadTooLargeError,
  SendlibPlanRequiredError,
  SendlibRateLimitError,
  SendlibTimeoutError,
  SendlibValidationError,
} from '@sendlib/node-sdk';
export type {
  Attachment,
  BatchRecipient,
  BatchRecipientResult,
  BatchRecipientStatus,
  BatchStatus,
  BatchStatusResponse,
  BatchVariables,
  CreateBatchInput,
  CreateBatchResponse,
  CustomEmailInput,
  DeliverabilityField,
  DeliverabilityInput,
  DeliverabilityIssue,
  DeliverabilityIssueCode,
  DeliverabilityManualCheck,
  DeliverabilityManualCheckCode,
  DeliverabilityReport,
  EmailAddress,
  EmailRecipient,
  KnownBatchRecipientStatus,
  SendEmailDebug,
  SendEmailInput,
  SendEmailResponse,
  SendlibApiErrorOptions,
  SendlibAuthMode,
  SendlibBatches,
  SendlibCallOptions,
  SendlibDeliverability,
  SendlibEmails,
  SendlibFetch,
  SendlibOptions,
  SendlibTemplates,
  TemplateData,
  TemplateEmailInput,
  TemplateSendInput,
  WaitForBatchOptions,
} from '@sendlib/node-sdk';
